# Generated by Django 3.2.4 on 2021-06-16 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 17, 15, 37, 794207, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
